### ISSUE TITLE
[Bug Report] Canceling pin entry should cancel phone number verification

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#3728] opened 2020-05-05 21:35 UTC
### Expected Behavior

1. Skip phone number verification at initialization
2. Start phone number verification from the settings menu
3. Cancel pin entry when prompted
4. (Expected) Phone number verification is canceled

### Current Behavior

After 3, phone number verification appears to continue and the "cancel" button in the upper-left corner is disabled. Android back button still allows exiting that screen.

**Comment by tarikbellamine** [comment] 2020-06-25 18:41
Duplicate of #4166

**Closed as completed by tarikbellamine** 2020-06-25 18:41 UTC
Labels: bug
