### ISSUE TITLE
Wallets logs are hard to access/see on iOS

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#4023] opened 2020-06-05 15:48 UTC
### Expected Behavior

Logs should be easily viewable and shareable, similar to what we do on Android.

### Current Behavior

Unless you launch the app via Xcode, it's hard to see all the logs from the wallet (Geth, React Native, system, etc).
Also you currently have to call `GethSetVerbosity` from the native side to change the Geth logs verbosity.

**Comment by tarikbellamine** [comment] 2020-09-17 22:25
Duplicate of #4751

**Closed as completed by tarikbellamine** 2020-09-17 22:25 UTC
