### ISSUE TITLE
Rename salt references to pepper

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#5117] opened 2020-09-18 16:13 UTC
### Expected Behavior

`salt` references in names + state -> `pepper`

### Current Behavior

PGPNP was renamed to ODIS and Salt renamed to Pepper across the monorepo except the wallet.

**Comment by nityas** [comment] 2020-12-01 01:08
duplicate of #4758

**Closed as completed by nityas** 2020-12-01 01:08 UTC
