### ISSUE TITLE
Devs SNBAT commit unit tests with .only's

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#513] opened 2019-08-14 18:51 UTC
### Expected Behavior

Lint checks fail if any `.only`s are left in mocha tests.

### Current Behavior

`.only`s can be mistakenly left behind, stopping Circle CI from running tests.

### Potential Solution

There's some ts-lint plugins that might help. I personally haven't been able to integrate them into our linter:
* https://www.npmjs.com/package/tslint-mocha-typescript-no-only
* https://github.com/microsoft/tslint-microsoft-contrib

**Comment by tkporter** [comment] 2019-08-14 20:04
Pretty much a dupe of #314

**Closed as completed by tkporter** 2019-08-14 20:04 UTC
