### ISSUE TITLE
Revoke for other groups always left 1

### ISSUE THREAD

**Issue by wjdfx** [celo-org/celo-monorepo#2511] opened 2020-01-23 14:41 UTC
### Expected Behavior

User can’t revoke all token from a group. It’s always left 1 token on the election:show xxx —voter list. Debug log see attach.

[message.txt](https://github.com/celo-org/celo-monorepo/files/4103588/message.txt)

### Current Behavior

celocli election:show 116a647ce0e9a012099508f285a7735f86e333a4 --voter
Running Checks:
   ✔  116a647ce0e9a012099508f285a7735f86e333a4 is a registered Account
address: 116a647ce0e9a012099508f285a7735f86e333a4
votes:
  0:
    group: 0x93c110Dc9812dc075C1541b2c5D1030B2Ad6C293
    pending: 0
    active: 1
  1:
    group: 0xCd061dF755F558A5ea809EA1589b0f8a5a5Bfa27
    pending: 0
    active: 1
  2:
    group: 0x2947EA31ab65B1FEE886DC6c113F79B222c804B7
    pending: 0
    active: 1

celocli election:revoke --for 0x2947EA31ab65B1FEE886DC6c113F79B222c804B7 --from 0x116a647Ce0E9A012099508f285a7735F86e333A4 --value 1
Running Checks:
   ✔  0x116a647Ce0E9A012099508f285a7735F86e333A4 is Signer or Account
   ✔  0x2947EA31ab65B1FEE886DC6c113F79B222c804B7 is ValidatorGroup
SendTransaction: revoke
txHash: 0xbe179973023c57efc847d7a957f7bbdd818e8eb9a41745cedac90e2e290b4bab
Sending Transaction: revoke... done

celocli election:show 116a647ce0e9a012099508f285a7735f86e333a4 --voter
Running Checks:
   ✔  116a647ce0e9a012099508f285a7735f86e333a4 is a registered Account
address: 116a647ce0e9a012099508f285a7735f86e333a4
votes:
  0:
    group: 0x93c110Dc9812dc075C1541b2c5D1030B2Ad6C293
    pending: 0
    active: 1
  1:
    group: 0xCd061dF755F558A5ea809EA1589b0f8a5a5Bfa27
    pending: 0
    active: 1
  2:
    group: 0x2947EA31ab65B1FEE886DC6c113F79B222c804B7
    pending: 0
    active: 1

**Comment by mrsmkl** [comment] 2020-01-23 15:12
Duplicate of #2507

**Closed as completed by mrsmkl** 2020-01-23 15:12 UTC
