### ISSUE TITLE
Panic on mobile in selectIssuers transaction

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#2094] opened 2019-12-06 01:35 UTC
### Current Behavior

Crash on selectIssuers. Sometimes doesn't appear

```
                     Go  E  panic: runtime error: invalid memory address or nil pointer dereference
                         E  [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7b143e09a4]
                         E  goroutine 324 [running]:
                  GoLog  E  panic: runtime error: invalid memory address or nil pointer dereference
                     Go  E  github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).snapshot(0x400000cb40, 0x0, 0x0, 0x405, 0x5e6e84170b1cccfa, 0x1720722f21f406c8, 0x298a61c29bbf0e41, 0x862851f699768d4b, 0x0, 0x0, ...)
                         E      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/engine.go:730 +0xcc4
                         E  github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).getValidators(0x400000cb40, 0x405, 0x5e6e84170b1cccfa, 0x1720722f21f406c8, 0x298a61c29bbf0e41, 0x862851f699768d4b, 0x40024b88d0, 0x405)
                         E      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/backend.go:590 +0x5c
                         E  github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).GetValidators(0x400000cb40, 0x40027933c0, 0x5e6e84170b1cccfa, 0x1720722f21f406c8, 0x298a61c29bbf0e41, 0x862851f699768d4b, 0x0, 0x0, 0x0)
                         E      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/backend.go:258 +0x54
                         E  github.com/ethereum/go-ethereum/core/vm.(*numberValidators).Run(0x7b154a0938, 0x0, 0x0, 0x0, 0xd11b2609e91d3b85, 0x910d0896b2b2c034, 0x54b2e11d, 0x4003332a80, 0x0, 0x40024b8800, ...)
                         E      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/contracts.go:649 +0x128
                         E  github.com/ethereum/go-ethereum/core/vm.RunPrecompiledContract(0x7b14d32660, 0x7b154a0938, 0x0, 0x0, 0x0, 0x40021ec3c0, 0x4003332a80, 0x7b142be998, 0x400310e2a0, 0x7bf9000001, ...)
                         E      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/contracts.go:86 +0x1c4
                         E  github.com/ethereum/go-ethereum/core/vm.run(0x4003332a80, 0x40021ec3c0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
                         E      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm/evm.go:61 +0x2c8
                         E  github.com/ethereum/go-ethereum/core/vm.(*EVM).StaticCall(0x4003332a80, 0x7b14d2f980, 0x40024a92c0, 0x0, 0x0, 0x7bf9000000, 0x0, 0x0, 0x0, 0x1388, ...)```

**Comment by timmoreton** [comment] 2019-12-06 02:19
happened on mobile, i.e ultralight sync mode.

**Comment by jmrossy** [comment] 2019-12-06 09:44
Dupe of https://github.com/celo-org/celo-blockchain/issues/661

**Closed as completed by jmrossy** 2019-12-06 09:44 UTC
Labels: bug
