### ISSUE TITLE
Users SNBAT to see a blank screen when long pressing the send tab '+'

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#919] opened 2019-09-11 08:12 UTC
### Expected Behavior

Long pressing the send tab ('+') doesn't do anything special.

### Current Behavior

Long pressing the send tab ('+') displays a blank screen:

![image](https://user-images.githubusercontent.com/57791/64679663-770ec280-d47c-11e9-9856-154a0856ccaa.png)

**Comment by jmrossy** [comment] 2019-09-19 12:19
Dupe of #466

**Closed as completed by jmrossy** 2019-09-19 12:19 UTC
