### ISSUE TITLE
[Valora mobile app] Wrong handling of value from deeplink transaction

### ISSUE THREAD

**Issue by jsdmc** [celo-org/celo-monorepo#6830] opened 2021-02-01 13:53 UTC
Im working with celo dappkit that uses deeplinks to pass transaction data to Valora ("sign_tx" type). And it turned out that for some precise values (18 digits decimals) Valora changes passed value and that causes an error. I guess it's a bug when string value was casted to number. That's a value I passed  to Valora - 283577701866387210
And thats the value Valora applied in param of transaction - 283577701866387200

This is a transaction
https://alfajores-blockscout.celo-testnet.org/tx/0xb84f7aaeec8fb2fd7793e02d336824232e3533220054cc52d565d3956918a741/raw_trace

I'm not familiar with Valora sources. But it's definitely a bug in the place where deeplink values are parsed.

**In addition to investigation, we should also add error handling for cases like these. If something goes wrong on the Valora side requests just hang and you're never sent back to the DApp**

**Comment by jsdmc** [comment] 2021-02-05 09:16
@critesjosh I'm sure it's not about sdk. I debugged, all values in deeplink are correct. It's Valora app changes values.

**Comment by critesjosh** [comment] 2021-02-05 14:09
Thanks @jsdmc I let the wallet team know and they are going to prioritize this issue soon

**Comment by jsdmc** [comment] 2021-02-09 14:30
Here is example of deeplink request that is causing problems
`celo://wallet/dappkit?type=sign_tx&requestId=deposit&callback=http%3A%2F%2Flocalhost%3A3000%2F%23%2Fdeposit%2FCELO%2F0.07466996135339098215&dappName=Moola&txs=W3sidHhEYXRhIjoiMHhkMmQwZTA2NjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWUwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTA5NDdlZjI5ZGM2Yjg2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsImVzdGltYXRlZEdhcyI6MjAwMDAwMCwiZnJvbSI6IjB4MDdlZjI5MGM5Y2M2MDIxOTFiNmQ4MDY4OThhMjFmNjA4NTcxMzQzMiIsInRvIjoiMHhjMTU0OEY1QUExRDc2Q0RjQUI3Mzg1RkE2QjVjRUE3MGY5NDFlNTM1Iiwibm9uY2UiOjI3LCJ2YWx1ZSI6Ijc0NjY5OTYxMzUzMzkwOTgyIn1d`

**Comment by jsdmc** [comment] 2021-02-09 14:30
And that's error I can take from logs
```
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xbac27a1a68d7922c4819881748b9650a797d2704feb30a8fc322ae3f005e6d6c",
  "blockNumber": 5045880,
  "contractAddress": null,
  "cumulativeGasUsed": 328720,
  "from": "0x07ef290c9cc602191b6d806898a21f6085713432",
  "gasUsed": 173960,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xc1548f5aa1d76cdcab7385fa6b5cea70f941e535",
  "transactionHash": "0x06916a3bd0ecc997e58450f4770a73deee41279a7114eb167ca4e7675045650e",
  "transactionIndex": 1
}
```

**Comment by jsdmc** [comment] 2021-02-09 14:31
I guess a problem is somewhere around here
https://github.com/celo-org/celo-monorepo/blob/fce3df17d1df43c37e59a3cc6918cc1a788a7dad/packages/sdk/utils/src/dappkit.ts#L262

**Comment by aslawson** [comment] 2021-03-22 19:59
Adding DevX -- to confirm if problematic code is in dappkit as mentioned above (and fix if so). Or confirm that the problem is in Valora instead.

**Comment by eelanagaraj** [comment] 2021-04-09 13:39
Hey @jsdmc, I haven't been able to reproduce this issue. I created cUSD transfers with a toy DApp (using the same value above, with cUSD as the gas fee currency) but don't observe the value being modified in Valora, or in the section of the code you pointed to, or in the final transaction that appeared on chain.

If you have any additional info on the following, that would be really helpful!
- Did you see this issue for all transactions, or where there particular transactions (i.e. with specific contracts, gas fees, values) that triggered this issue? Are these reproducible or does it occur only sometimes?
- Does this occur in the Alfajores Wallet as well as Valora? If not, which one does it occur on?
- Does this occur for the newest versions of Alfajores Wallet/Valora and dappkit?

Feel free to message me on Discord as well if that's easier. Thanks!

**Comment by eelanagaraj** [comment] 2021-04-14 12:40
Chatted on Discord -- closing this issue for now since we can't reproduce.

**Closed as completed by eelanagaraj** 2021-04-14 12:40 UTC
Labels: bug
