### ISSUE TITLE
 'Payments of # Celo dollars ' push notification is received even though user has selected different currency

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2725] opened 2020-02-11 13:12 UTC
**Frequency:** 100%
**App version:** Play Store build : 1.6.0 (104794306)
**Repro on:** Samsung Galaxy A5 (7.0), Redmi Note 7 Pro (9.0)
**Testing Account:**13158358979 /[backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1) Launch the app and login with testing account in device 1.
2) Launch the app and login with testing account in device 2. 
3) Change the currency other than the USD from device 1. 
4) Put the app in background mode from the device 1. 
5) Send the payment or payment request from device user 2 to device user 1
6) Observe 'Payments of # Celo dollars ' push notification is received

**Current Behavior:**  'Payments of # Celo dollars ' push notification is received
**Expected Behavior:**  'Payments of # ' push notification is received as per the selected currency. 
**Attachment:** [Android_Push notification received.mp4 .mp4](https://drive.google.com/file/d/1dk6Wh2IIpzkQDr6XR3DCgURwz544BgGo/view?usp=sharing) (Bug observe at 35 sec)

**Comment by annakaz** [comment] 2020-07-22 21:23
Duplicate of https://github.com/celo-org/celo-monorepo/issues/2153

**Closed as completed by annakaz** 2020-07-22 21:23 UTC
Labels: bug
