### ISSUE TITLE
StatefulSet validators SBAT export metrics to Stackdriver

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#523] opened 2019-08-14 19:06 UTC
### Expected Behavior

geth-exporter and geth-to-sd export metrics to Stackdriver monitoring on validator Pods.

### Current Behavior

Unknown

**Comment by tkporter** [comment] 2019-09-11 04:31
Dupe of #693, closing

**Closed as completed by tkporter** 2019-09-11 04:31 UTC
