### ISSUE TITLE
Developers SBAT request arbitrary signatures using dappkit

### ISSUE THREAD

**Issue by critesjosh** [celo-org/celo-monorepo#5901] opened 2020-11-17 18:04 UTC
### Expected Behavior

Developers should be able to ask users to sign arbitrary data with a Celo Wallet using dappkit.

### Current Behavior

Developers can only ask users to sign transactions.

**Comment by aslawson** [comment] 2021-03-10 01:15
From @AlexBHarley 
The issue is primarily on [Valora's] side, it's easy for us to amend dappkit once they support personal_sign and eth_signTypedData
Those two are definitely the most important actions to support after signTransaction but there are more such as computeSharedSecret and decrypt if we want full wallet compatibility. 

TODO: @aslawson to chat with Valora

**Comment by AlexBHarley** [comment] 2021-07-08 12:11
@nambrot I assume this wasn't supposed to come over to Contracts/Identity?

Will close this as we've migrated towards WalletConnect and have support for personal_sign and eth_signTypedData.

**Closed as completed by AlexBHarley** 2021-07-08 12:11 UTC
