### ISSUE TITLE
[Android] Exchange activity takes a long time (3-4 Minutes) to exchange the cUSD to cGLD when device network connectivity is low even though Celo Lite toggle is ON 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1436] opened 2019-10-23 12:04 UTC
**Frequency:** 100%
**App version:**  staging build v1.5.0  (101548577) 
**Repro on:** Samsung Galaxy Grand Prime (5.1.1), Samsung Galaxy s5 (6.0.1) 
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Pre-condition:** Mobile network should be connected to either 2G or 3G. 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the “Gold” tab. 
3) Tap on the Exchange button. 
4) Enter an amount in cUSD field. 
5) Tap on the Continue button. 
6) Tap on the “Exchange” button. 
7) Wait for a moment and observe. 

**Investigation:**
1)  Issue does not repro when device is connected with a good internet connection 
2) After 3-4 minutes cUSD to cGLD is exchanged
**Current Behavior:** “Confirming...” text is shown continuously on “Exchange” activity 
**Expected Behavior:** User should be able to do exchange activity with low connectivity network when Celo Lite toggle is enabled 
**Attachment:** [Android_ExchangeTakesTime.mov](https://drive.google.com/file/d/1rDQXGLihn1iqQUK2vdyNAAUsyKY2QV4V/view?usp=sharing) (Bug observe after 40 sec)

**Comment by Lss-Ankit** [comment] 2019-11-13 06:11
Verified with Android build v1.5.1 (Pilot Network) and observed that the issue is still reproduced. 

- Exchange activity takes a long time (3-4 Minutes) to exchange the cUSD to cGLD when device network connectivity is low even though Celo Lite toggle is ON

**Comment by annakaz** [comment] 2019-12-16 22:36
Closing as this is a duplicate of https://github.com/celo-org/celo-monorepo/issues/1741

**Closed as completed by annakaz** 2019-12-16 22:36 UTC
Labels: bug
