### ISSUE TITLE
[Android]  “Sorry Something went wrong” screen is always shown when user taps on “QR code” and “Cog” icon after removing the user name from user profile. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1063] opened 2019-09-20 09:19 UTC
**Frequency:** 100%
**App version:** Celo staging v1.4.2
**APK File:** app-armeabi-v7a-staging, app-x86-staging.
**Repro on:**  Samsung Galaxy Note 5 (7.0), Samsung galaxy note 9 (9.0)  
**Priority:** High
**Testing Account:** 415 295 8433/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)
 
**Repro Steps:** 
1. Launch the app. 
2. Tap on the Cog icon. 
3. Tap on the Edit profile. 
4. Tap on the Edit name option. 
5. Remove the user name. 
6. Tap on “Done” button. 
7. Observe. 
 
**Investigation:** The issue is still repro after kill and relaunch or restart the app. 
**Impact:** The user is blocked to use the QR code and Celo setting screen. 

***Expected Behavior***
Validation message is shown instead of "Something went wrong" screen when the user removes the user name and user should be able to use QR code and Setting page

***Current Behavior***
 “Sorry, Something went wrong” screen is always shown when user taps on the “QR code” and “Cog” icon after removing the user name from the user profile. 

**[Attachment:](https://drive.google.com/file/d/1GB66zjYKVyQkRfmjuXbNifGD8ZAk7OTP/view?usp=sharing)**  (Bug Observe at 08 sec)

**Comment by Lss-Ankit** [comment] 2019-10-07 10:22
@jmrossy Verified with the Android play store build v1.5.0 and found that the issue is still reproduced.
Attachment: [Android_SomthingWentWrongError.mp4](https://drive.google.com/file/d/1-8oNEfbYocoN4Sr3UtwvbSssdV4iOqcG/view?usp=sharing) (Bug observe at 12 and 30 sec)

**Comment by Lss-Ankit** [comment] 2019-10-24 13:16
@jmrossy Verified with iOS test flight build v1.5.0 and observe that issue: “Sorry Something went wrong” screen is always shown when user taps on “QR code” and “Cog” icon after removing the user name from user profile.

Attachment: [EditProfileIssue.mp4](https://drive.google.com/file/d/10mCxi73-b4noZEVeqLeHtuoTPXIugjML/view?usp=sharing)

**Comment by i1skn** [comment] 2019-11-01 14:44
I can reproduce it and think it has already been fixed here: https://github.com/celo-org/celo-monorepo/pull/1454. So this issue might be just a duplicate of https://github.com/celo-org/celo-monorepo/issues/1238.

**Closed as completed by i1skn** 2019-11-01 14:44 UTC
Labels: bug

**Comment by Lss-Ankit** [comment] 2019-11-20 13:07
@jmrossy and @i1skn Verified with Android build v1.5.1 (Pilot Network) and observed that issue is fixed as now “Sorry Something went wrong” screen is not shown. 

There should be some validation that the user name should not be blank. 
**Note:** If user has not set there name then "Mobile #" is shown under the user profile pic. 

Attachment: [ Android_EditName.mp4](https://drive.google.com/file/d/1fwvjR2I9WWbMbhQVPfoU0RD4ZYPYmtuG/view?usp=sharing)
