### ISSUE TITLE
Android: User is able to access invite/exchange notification even though ‘Get Backup key’ blue color header is shown on wallet tab

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3095] opened 2020-03-12 09:12 UTC
**Frequency:** 100%
**iOS App version:** Android Playstore build : 1.6.1 (104794404).
**Repro on Android Device:** Samsung Galaxy Note 9 (10)

**Prerequisites:** 
1) Make sure ‘Get Backup key’ blue color header is shown on ‘Wallet’ tab 
2) User should have ‘Payment Requested’ & ‘Invite Friend to Celo’ notification on ‘Wallet’ tab 

**Repro Steps:** 
1) Launch the app and Register with any account 
2) Wait till ‘Get Backup Key’ blue header is shown (~24 hours)
3) Tap on ‘Invite’ option from ‘Invite Friend to Celo’ notification (Bug)
4) Tap on ‘Pay’ option from ‘Payment Requested’ notification (Bug) 

**Current Behavior:** User is able to access invite/exchange notification when ‘Get Backup key’ blue color header is shown

**Expected Behavior:** User should not be able to access the invite/exchange notification when ‘Get Backup key’ blue color header is shown

**Investigation:** ‘Invite’ & ‘Gold’ tab are shown disabled 

**Attachment:**  [Android_GetbackupKey with blue header.png](https://drive.google.com/file/d/17nSBpA3NnCEKd_-r56KeguINHaaAD9Cf/view?usp=sharing)

**Comment by tarikbellamine** [comment] 2020-09-17 00:24
Duplicate of #4085

**Comment by Lss-Ankit** [comment] 2020-10-05 12:11
Hi @tarikbellamine  Earlier account is frozen however user is able to access  CTA (Invite/Exchange notifications)  shows on in app. 

Now, on #4085 issue is that account is not frozen even though Get Backup Key blue color banner is shown. 
both issue are related to Get Backup key blue banner but both are different issue.

**Comment by tarikbellamine** [comment] 2020-10-05 16:16
I view this as a subset of #4805. If an an account is frozen, the user should not be able to access anything (even the notifications).

**Closed as completed by tarikbellamine** 2020-10-05 16:16 UTC
Labels: bug
