### ISSUE TITLE
Everyone SBAT reference service owner roles and accountabilities

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#368] opened 2019-08-07 15:46 UTC
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by nambrot** [comment] 2019-08-21 04:05
Closing as a dupe of https://github.com/celo-org/celo-labs/issues/36

**Closed as completed by nambrot** 2019-08-21 04:05 UTC
