### ISSUE TITLE
Settings -> Licenses error loading page

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1519] opened 2019-10-29 23:01 UTC
iOS 13.2, iPhone 8

### Expected Behavior

Licenses are correctly shown

### Current Behavior

![IMG_15E486CF8721-1](https://user-images.githubusercontent.com/20362969/67815854-4e12b300-fa65-11e9-8d5c-553c805a8006.jpeg)

**Comment by jmrossy** [comment] 2019-11-06 14:52
Dupe of #1459

**Closed as completed by jmrossy** 2019-11-06 14:52 UTC
Labels: bug
