### ISSUE TITLE
phone numbers and country automatically SBAT be read automatically

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#886] opened 2019-09-09 22:39 UTC
### Expected Behavior

read both the country and phone number automatically, present both as a placeholder so the user can edit if incorrect.

If there are multiple phone numbers detected, present the default modal with options to prompt the user to select the correct one.

### Current Behavior

We make the user input their country and phone number

**Comment by jmrossy** [comment] 2019-09-10 13:53
Dupe of #654

**Closed as completed by jmrossy** 2019-09-10 13:53 UTC
