### ISSUE TITLE
"Confirming..." shown in feed after transaction has been rejected

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5275] opened 2020-10-06 17:14 UTC
### Expected Behavior

feed item should show an error state when the transaction cannot be completed & removed from feed

### Current Behavior

https://celo-org.slack.com/archives/C018VLA3YAK/p1601666037020700

**Comment by tarikbellamine** [comment] 2020-10-07 19:38
Duplicate of #5257. I also marked this as a P2 because it does not impact functionality.

**Closed as completed by tarikbellamine** 2020-10-07 19:38 UTC
Labels: bug
