### ISSUE TITLE
election:vote throws `gas required exceeds allowance`

### ISSUE THREAD

**Issue by 1xCL** [celo-org/celo-monorepo#2301] opened 2019-12-19 04:41 UTC
### Expected Behavior

Voting should work regardless of non-voting locked gold amount.

### Current Behavior

Voting with 1000 or bigger non-voting locked gold throws an error.
```
$ celocli election:vote --from $CELO_VALIDATOR_ADDRESS --for $CELO_VALIDATOR_GROUP_ADDRESS --value 1000000000000000000000
Running Checks:
   ✔  9913e776ed11e9247ef89b4e8b2b7c062faa5281 is Signer or Account
   ✔  96b473b7a71f1a3804ad306af4f07f86c796eff5 is ValidatorGroup
   ✔  Account has at least 1000 non-voting Locked Gold
Sending Transaction: vote... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.asdf/installs/nodejs/10.16.3/.npm/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```
But voting with smaller amount works.
```
$ celocli election:vote --from $CELO_VALIDATOR_ADDRESS --for $CELO_VALIDATOR_GROUP_ADDRESS --value 100000000000000000000
Running Checks:
   ✔  9913e776ed11e9247ef89b4e8b2b7c062faa5281 is Signer or Account
   ✔  96b473b7a71f1a3804ad306af4f07f86c796eff5 is ValidatorGroup
   ✔  Account has at least 100 non-voting Locked Gold
SendTransaction: vote
txHash: 0x3b63779cae0e2dc512962011b18e3749e1e2c9f6e56f18ecd1b1195891049190
Sending Transaction: vote... done
```

```
$ celocli version
@celo/celocli/0.0.32-beta3 linux-x64 node-v10.16.3
```
```
$ celocli lockedgold:show $CELO_VALIDATOR_ADDRESS
Running Checks:
   ✔  9913e776ed11e9247ef89b4e8b2b7c062faa5281 is a registered Account
lockedGold:
  total: 50902661988749630725515 (~50902.66 10^18)
  nonvoting: 11652906246891594842112 (~11652.91 10^18)
  requirement: 10000000000000000000000 (~10000 10^18)
pendingWithdrawals:
```
```
$ celocli account:balance $CELO_VALIDATOR_ADDRESS
All balances expressed in units of 10^-18.
goldBalance: 9970013280
dollarBalance: 0
```

**Comment by nategraf** [comment] 2020-01-10 01:21
Sorry for the slow response. I was trying to reproduce this just now and couldn't. Have you seen this again and do any more information to help reproduce.

**Comment by bgeihsgt** [comment] 2020-01-11 04:38
I hit this as well. If you could let me know some commands to run to troubleshoot, I can help.

**Comment by bgeihsgt** [comment] 2020-01-11 04:38
I'm on `0.0.33`

**Comment by bgeihsgt** [comment] 2020-01-11 05:16
Did some debugging and saw this is where it is failing

```
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 13,
  web:rpc:payload   method: 'eth_estimateGas',
  web:rpc:payload   params:
  web:rpc:payload    [ { from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: '0x0',
  web:rpc:payload        data:
  web:rpc:payload         '0x580d747a000000000000000000000000d4e068fb4467816c768fa3460ce9d5ae5642de3700000000000000000000000000000000000000000000028a401093c42a8a75780000000000000000000000001b1df7e851208f39d2a34cadcf0b34c48f47faef00000000000000000000000096b473b7a71f1a3804ad306af4f07f86c796eff5',
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x918919436bba96e2c80ca22405aaba075e2ac82e' } ] } +40ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 13,
  web:rpc:response   error:
  web:rpc:response    { code: -32000,
  web:rpc:response      message:
  web:rpc:response       'gas required exceeds allowance or always failing transaction' } } +185ms
```

**Comment by bgeihsgt** [comment] 2020-01-11 05:17
This is a total shot in the dark, but is this at all related to https://github.com/ethereum/go-ethereum/issues/18519 ?

**Comment by bgeihsgt** [comment] 2020-01-11 05:24
More data (hope this data isn't sensitive :P )

```
web:rpc:payload { jsonrpc: '2.0', id: 1, method: 'eth_syncing', params: [] } +0ms
  web:rpc:response { jsonrpc: '2.0', id: 1, result: false } +0ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 2,
  web:rpc:payload   method: 'eth_getBlockByNumber',
  web:rpc:payload   params: [ 'latest', false ] } +39ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 2,
  web:rpc:response   result:
  web:rpc:response    { difficulty: '0x1',
  web:rpc:response      extraData:
  web:rpc:response       '0xd983010817846765746889676f312e31312e3133856c696e7578000000000000f8c7c0c080b841fd3a67babe8ad780c7c00c63aa4ee00689e8c067b21668c52979a09db5ea6ba516866c07452b21d6c3ca0b3e0868ff5bc7b680ab26461ffcb38c6dc6221f0b1a01f83e8b3847636febe5af7b6ffb6eb0e73f2948a4710c3427f5a6e071186fc649e16c50846cf7a893312dc81c67350c9b33756f37adab6c78e64102b7ef538180f83e8b7fffffffffffffffffffffb0f36f6c508b01cf1fdb373eb0d69b9eb79c90d380c013e24cff5dd7ef7d1d5a3300603668a422ce5fd07749cb38842d818080',
  web:rpc:response      gasLimit: '0x1312d00',
  web:rpc:response      gasUsed: '0x0',
  web:rpc:response      hash:
  web:rpc:response       '0x0a5e75fa85413acc20ffd68bf00241ee0d4df552f1f4277bc5880ec007e9ee8f',
  web:rpc:response      logsBloom:
  web:rpc:response       '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  web:rpc:response      miner: '0x506e7282f5492825739b42b488754e99ff3d21a9',
  web:rpc:response      mixHash:
  web:rpc:response       '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365',
  web:rpc:response      nonce: '0x0000000000000000',
  web:rpc:response      number: '0x12a1',
  web:rpc:response      parentHash:
  web:rpc:response       '0x50edce8ac2563dfa2acced2d4bb0fa2f9acee69b840efaebc7ff3cea11b11c1a',
  web:rpc:response      randomness:
  web:rpc:response       { committed:
  web:rpc:response          '0x5ace1d83bf219038d2d3927e9e0124fc7d696e71f201200715d8aedf9f9f4211',
  web:rpc:response         revealed:
  web:rpc:response          '0xbff2d6ad17c0fff94a4acd3dd8bbd6e0d4b300123e28e21a788c9505222316f9' },
  web:rpc:response      receiptsRoot:
  web:rpc:response       '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  web:rpc:response      sha3Uncles:
  web:rpc:response       '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  web:rpc:response      size: '0x32d',
  web:rpc:response      stateRoot:
  web:rpc:response       '0x2308c98f89df03c61d56f50ae6aad9b05d69f09a62b0ecd8dd2611a1b24e728d',
  web:rpc:response      timestamp: '0x5e1958df',
  web:rpc:response      totalDifficulty: '0x12a2',
  web:rpc:response      transactions: [],
  web:rpc:response      transactionsRoot:
  web:rpc:response       '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  web:rpc:response      uncles: [] } } +8ms
Running Checks:
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 3,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0xdd927233065b3511e672769036815d78dd1d8a43df1e790e38323f22c4aed211e85ea281',
  web:rpc:payload        from: undefined,
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x000000000000000000000000000000000000ce10' },
  web:rpc:payload      'latest' ] } +44ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 3,
  web:rpc:response   result:
  web:rpc:response    '0x00000000000000000000000062492a644a588fd904270bed06ad52b9abfea1ae' } +47ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 4,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0x25ca4c9c000000000000000000000000b84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x62492a644a588fd904270bed06ad52b9abfea1ae' },
  web:rpc:payload      'latest' ] } +16ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 4,
  web:rpc:response   result:
  web:rpc:response    '0x0000000000000000000000000000000000000000000000000000000000000001' } +22ms
   ✔  b84fa68db82af1bfcbb4b876e017657afb1dd615 is Signer or registered Account
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 5,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0xdd92723349dc7107d41d3c01a9f941a7d9a9f9177349b5521aeb56861470e42cf05da2ee',
  web:rpc:payload        from: undefined,
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x000000000000000000000000000000000000ce10' },
  web:rpc:payload      'latest' ] } +18ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 5,
  web:rpc:response   result:
  web:rpc:response    '0x000000000000000000000000e8e4969649330b25c13a36f977487084b92a7466' } +19ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 6,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0x93c5c487000000000000000000000000b84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x62492a644a588fd904270bed06ad52b9abfea1ae' },
  web:rpc:payload      'latest' ] } +26ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 6,
  web:rpc:response   result:
  web:rpc:response    '0x000000000000000000000000b84fa68db82af1bfcbb4b876e017657afb1dd615' } +30ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 7,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0x52f13a4e000000000000000000000000d4e068fb4467816c768fa3460ce9d5ae5642de37',
  web:rpc:payload        from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0xe8e4969649330b25c13a36f977487084b92a7466' },
  web:rpc:payload      'latest' ] } +22ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 7,
  web:rpc:response   result:
  web:rpc:response    '0x0000000000000000000000000000000000000000000000000000000000000001' } +10ms
   ✔  d4e068fb4467816c768fa3460ce9d5ae5642de37 is ValidatorGroup
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 8,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0xdd9272333d744b38c539f9c7aabe18c37da0535bb6322568ef752e312c624287c915ee69',
  web:rpc:payload        from: undefined,
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x000000000000000000000000000000000000ce10' },
  web:rpc:payload      'latest' ] } +14ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 8,
  web:rpc:response   result:
  web:rpc:response    '0x0000000000000000000000007c08fec4da47ebece57de73204bd632ddac91027' } +19ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 9,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0x93c5c487000000000000000000000000b84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x62492a644a588fd904270bed06ad52b9abfea1ae' },
  web:rpc:payload      'latest' ] } +17ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 9,
  web:rpc:response   result:
  web:rpc:response    '0x000000000000000000000000b84fa68db82af1bfcbb4b876e017657afb1dd615' } +12ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 10,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0x3f199b40000000000000000000000000b84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x7c08fec4da47ebece57de73204bd632ddac91027' },
  web:rpc:payload      'latest' ] } +20ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 10,
  web:rpc:response   result:
  web:rpc:response    '0x00000000000000000000000000000000000000000000028a401093c42a8a7578' } +22ms
   ✔  Account has at least 11994.999999999999899 non-voting Locked Gold
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 11,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data:
  web:rpc:payload         '0xdd927233235a6f54090e9b94aa4e585a699c4375a2ff8f572c68114d138f0ed121527849',
  web:rpc:payload        from: undefined,
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x000000000000000000000000000000000000ce10' },
  web:rpc:payload      'latest' ] } +31ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 11,
  web:rpc:response   result:
  web:rpc:response    '0x000000000000000000000000918919436bba96e2c80ca22405aaba075e2ac82e' } +32ms
  web:rpc:payload { jsonrpc: '2.0',
  web:rpc:payload   id: 12,
  web:rpc:payload   method: 'eth_call',
  web:rpc:payload   params:
  web:rpc:payload    [ { data: '0x7046c96b',
  web:rpc:payload        from: '0xb84fa68db82af1bfcbb4b876e017657afb1dd615',
  web:rpc:payload        gasPrice: undefined,
  web:rpc:payload        gas: undefined,
  web:rpc:payload        to: '0x918919436bba96e2c80ca22405aaba075e2ac82e' },
  web:rpc:payload      'latest' ] } +13ms
  web:rpc:response { jsonrpc: '2.0',
  web:rpc:response   id: 12,
  web:rpc:response   result:
  web:rpc:response    '0x000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000023000000000000000000000000b9211793effa1c3e2a48d76f891e791888eda9b2000000000000000000000000ac5e5336f96e63950fdcb40b1abd13b4224aeb4f0000000000000000000000001dbe73b0480058106798adda62e25d5279233c1b000000000000000000000000bcd25468e4d433ac442b87f32b37b39678bf7077000000000000000000000000e89897510bfb2fc0647325fb6d580594c061acbf000000000000000000000000412f2910970f81e49af9b46067d3fd4d7a281679000000000000000000000000d99bedef76c9caa7ec0cfdaa79c1b9330bb02061000000000000000000000000bfea1fc9870ee47c517faf53da39edd9cb2142fa0000000000000000000000009f79acea4994cc09f31f2fc87105aa619fa22020000000000000000000000000e7c85a3f18d18d40d713041a69d4795f36339f7d00000000000000000000000007f52046f4f90eb4e9667fa0d1ada8aed8f98ec20000000000000000000000006f46d495a492a212e330d20189a0656cf072836a00000000000000000000000062ced47f08c104920ffa023c8d8f75ff18fdfc1d000000000000000000000000675e639e4e19a22204bc1f5ea006e948413f796b00000000000000000000000096b473b7a71f1a3804ad306af4f07f86c796eff5000000000000000000000000c1c8432a07183e96043d00ce2a60d637cb50959000000000000000000000000041716bcf7c9a97179a7a276b153a7563e5f777eb0000000000000000000000003de7dddd7ea601097c78e874e914550c9ceb6950000000000000000000000000097623488573f87a02bbf292f9e78c0c751752e100000000000000000000000044edd5027f894058cfb4b519beb04f247336bc22000000000000000000000000035ef01395e2cc1219482f0542a05b627fac36b6000000000000000000000000fd82035569938d6b0b41552739b067c29a814006000000000000000000000000e6e140a4d01bedce295f7f4f6488432e97eedb2d000000000000000000000000e92cceae3c5c0a42d38fea440513dbcf655a25d9000000000000000000000000bcff1270b8aa83232b6d7113144557dfac93b591000000000000000000000000622c80811b0ece68ee915002d38e758484cf089b0000000000000000000000005061fa0911b386dad757888337d501fafda6082f0000000000000000000000001b1df7e851208f39d2a34cadcf0b34c48f47faef00000000000000000000000061b229d563b1b78f0941ae756a1e5ade63fd797500000000000000000000000010e338e2523594a18c8612222587976c624d8aa0000000000000000000000000a9c1b0ff35084afd146a8751193ddc33092d9b27000000000000000000000000fbe56e638dcf7e64f121af93bb4a326ab2bbaa5c0000000000000000000000008c3f4dffcfce925bbbd2c0cc0ddc3653378a414c000000000000000000000000d4e068fb4467816c768fa3460ce9d5ae5642de370000000000000000000000004418a99ac82d042971668a78604d1baaa92b895f000000000000000000000000000000000000000000000000000000000000002300000000000000000000000000000000000000000000152d02c7e14af67ffff1000000000000000000000000000000000000000000000a968163f0a57b4000000000000000000000000000000000000000000000000005150a36a7d0b03b0000000000000000000000000000000000000000000000000514fbb745f049577a00000000000000000000000000000000000000000000000514ef26dd2590380002000000000000000000000000000000000000000000000513f55a0483cb30000000000000000000000000000000000000000000000000050f9f20ec5f7bf0000000000000000000000000000000000000000000000000050f9f20ec5f7bf000000000000000000000000000000000000000000000000004ff5bcad1d752c0000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000043c33c193756480000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab240000000000000000000000000000000000000000000000000021e19e0c9bab24000000000000000000000000000000000000000000000000000000000000000018a880000000000000000000000000000000000000000000000000000000000000000' } +26ms```

**Comment by bgeihsgt** [comment] 2020-01-11 08:08
.....and now it works. Strange.

**Comment by aaronmboyd** [comment] 2020-01-11 14:15
@bgeihsgt Any steps to fix this or did you simply try again?

**Comment by aaronmboyd** [comment] 2020-01-11 14:20
Workaround:
Split your votes into two tranches, one for 10000 and one for the remainder. 
(Don't forget to leave enough for transactions)

**Comment by bgeihsgt** [comment] 2020-01-11 17:57
I didn’t do anything to fix it. Just tried a few hours later and it worked.

Note i tried that workaround but didn’t work for me while it was broken. I did 1000 then 10000 and then the rest of the amount didn’t work. I had plenty of unlocked gold for tx fees.

**Comment by nategraf** [comment] 2020-05-19 00:00
I am going to close this issue now because my understanding is that it hasn't been seen in a while, and if it does appear again #3428 will allow a more detailed issue to be opened.

**Closed as completed by nategraf** 2020-05-19 00:00 UTC
