### ISSUE TITLE
Lookup contact details in escrow payment reclaim components

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#2438] opened 2020-01-14 20:27 UTC
### Expected Behavior

EscrowedPaymentListItem and ReclaimPaymentConfirmationScreen should look up the recipient number in the recipientCache and show a name instead of a number if possible.

### Current Behavior

No lookup, we just show the phone number

**Comment by tarikbellamine** [comment] 2020-09-17 00:54
Duplicate of #4957

**Closed as completed by tarikbellamine** 2020-09-17 00:54 UTC
