### ISSUE TITLE
cEUR CLI documentation

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#7131] opened 2021-02-16 14:31 UTC
Update the CLI documentation to include information about cEUR.

TODO: list out which sections need updating

**Comment by martinvol** [comment] 2021-04-22 13:41
I reviewed the docs and we already have docs for `transfer:euros` and `exchange:euros`. Looks like it was generated automatically. Are we good to close this?

https://docs.celo.org/command-line-interface/commands/transfer

**Comment by martinvol** [comment] 2021-04-22 13:45
@barbaraliau confirmed me we're good to close!

**Closed as completed by martinvol** 2021-04-22 13:45 UTC
