### ISSUE TITLE
[ContractKit] Boolean calls handled incorrectly on exception

### ISSUE THREAD

**Issue by keefertaylor** [celo-org/celo-monorepo#3713] opened 2020-05-04 10:18 UTC
When making a call to a contract wrapper which returns a boolean, ContractKit will return `true` if a solidity `require()` statement triggers a revert op code. 

Consider the following program:
```javascript
import { newKit } from '@celo/contractkit'

const nodeURL = 'https://rc1-forno.celo-testnet.org/'
const kit = newKit(nodeURL)

const downtimeSlasherContract = await kit.contracts.getDowntimeSlasher()

const isDown = await downtimeSlasherContract.isDown(99999999999, 0, 0)
console.log(`isDown: ${isDown}`)
```

This program outputs `true`. However, block 99999999999 doesn't exist on RC1 yet, so [this require()](https://github.com/celo-org/celo-monorepo/blob/1e94c71956f8f534a3a499a38c6c17b6fac19074/packages/protocol/contracts/governance/DowntimeSlasher.sol#L62) is hit. 

The response is
```
0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002c656e6420626c6f636b206d75737420626520736d616c6c6572207468616e2063757272656e7420626c6f636b0000000000000000000000000000000000000000
```
which is a revert op code. ContractKit is interpreting this revert code as a boolean and returning `true`. 

Here's a complete debug log of the above program: https://gist.github.com/keefertaylor/a1dff437fb41703d06a9a903f5d9673a

### Expected Behavior

Contract kit throws an exception.

### Current Behavior

ContractKit returns true.

**Comment by keefertaylor** [comment] 2020-05-07 06:42
Hey folks,

Happy to write a PR for this but I am having trouble tracing down where the parsing is actually done. If you have a code pointer it is possible I could fix this myself.

**Comment by eelanagaraj** [comment] 2021-02-19 15:40
@keefertaylor I wasn't able to reproduce this (using a different function on `Accounts.sol` as the `isDown` function no longer exists for `DowntimeSlasher`). It looks like hitting a `require` within a Contract call is now raising an exception as expected. I'm going to go ahead and close this, but please reopen or open a new issue if you observe this with a different function! Thanks for flagging this in any case!

**Closed as completed by eelanagaraj** 2021-02-19 15:40 UTC
Labels: bug
