### ISSUE TITLE
“Review” button shows in disabled state when a user enters the 0.01 amount in “Amount (Gold/USD)” field while buying the Gold. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2534] opened 2020-01-24 12:21 UTC
**Frequency:** 100%
**App version:** Integration build v1.5.2 (101548777) 
**Repro on:** Google Pixel XL 2 (9.0), Samsung Galaxy A8+ (8.0.0) 

**Repro Steps:** 

1) Launch the app.  
2) Tap on Gold tab. 
3) Tap ”Buy” button. 
4) Enter an 0.01 amount. 
5) The Observe review button is shown disabled state. 

**Investigation:** 
1) Review button shows enabled when a user enters 0.01 amount in Amount (Gold/USD) field while selling the gold. 
2) Review button shows in disabled state when the user enters 0.001 amount in the Amount (Gold/USD) field while selling the gold. 

**Current Behavior:** “Review” button shows in disabled state
**Expected Behavior:** “Review” button should show enabled. 
**Impact:** user is blocked to exchange with minimum amount
**Attachment:** [Android_ReviewButtonIssue.mp4](https://drive.google.com/file/d/1f-oGbHVU9tn4JSzGxpZbAPXBLvh26oKv/view?usp=sharing) (Bug Observed after 07  sec)

**Comment by annakaz** [comment] 2020-01-29 17:00
Duplicate of https://github.com/celo-org/celo-monorepo/issues/2595

**Closed as completed by annakaz** 2020-01-29 17:00 UTC
Labels: bug

**Comment by Lss-Ankit** [comment] 2020-06-18 11:48
Verified with Android play store build v1.8.2 and test flight build v1.8.2 (38) found that review button is shown enabled when user entering 0.01 amount in Amount (Gold/USD) field
