### ISSUE TITLE
[Wallet] Green screen on app open

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2986] opened 2020-02-27 08:06 UTC
When you launch the app:

### Expected Behavior

green splash screen with celo logo, wallet home

### Current Behavior

green splash screen with celo logo, green splash (no logo), wallet home

reported by @jeanregisser

**Comment by i1skn** [comment] 2020-02-27 08:17
I've found why it's happening: 
https://github.com/celo-org/celo-monorepo/blob/cfb830a65c7010d57ff83fb3ae27c723b41d9b6d/packages/mobile/src/app/AppLoading.tsx#L68

But I'm puzzled, why we did not see it before or was it just too fast? @jeanregisser @jmrossy thoughts?

**Comment by Lss-Ankit** [comment] 2020-02-27 08:42
Hey @i1skn i have filed similar issue: https://github.com/celo-org/celo-monorepo/issues/1276# issue-504616878 and it is in closed status as it intended behavior.

**Comment by i1skn** [comment] 2020-02-27 08:45
@Lss-Ankit thanks a lot for providing reference to the previous issue!

**Comment by Lss-Ankit** [comment] 2020-02-27 08:49
@i1skn Welcome!!

**Comment by jeanregisser** [comment] 2020-02-27 08:56
yes I think it was too fast and we didn't really notice. So looks like the timings have changed now.
What's the difference with what we were doing previously?

**Comment by i1skn** [comment] 2020-02-27 09:00
@jeanregisser I think if that's an issue and not an intended behavior, we should not rely on `App` loading speed, cause it may differ on different devices. What do you think?

**Comment by Lss-Ankit** [comment] 2020-02-27 09:01
@jeanregisser Previously i have observed an issue by reproducing below steps: 
1. Launch the app.
2. Make sure user is on ‘Choose Language’ page.
3. Tap device back button to close the app.
4. Relaunch the app.
5. Observe

Title: App logo is not shown after launching it when app is closed by tapping on device back button.

**Comment by jeanregisser** [comment] 2020-02-27 09:35
Yes we shouldn't rely on timings and only dismiss the splash with the logo when the app is truly ready.

My hunch is the recent addition of the async call here revealed this bug we had:
https://github.com/celo-org/celo-monorepo/blob/fa21743b4f30aca2f112cc48f6442b1b091cba3d/packages/mobile/src/app/saga.ts#L108

Looks like one fix would be to move the splash hiding logic to that saga instead of in https://github.com/celo-org/celo-monorepo/blob/fa21743b4f30aca2f112cc48f6442b1b091cba3d/packages/mobile/src/app/App.tsx#L73

**Closed as completed** 2020-03-13 20:18 UTC
Labels: bug
