### ISSUE TITLE
[cli] [contractkit] Support removing attestation signer

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#6397] opened 2021-01-07 00:51 UTC
### Expected Behavior

`celocli account:deauthorize --role [attestation]`

Valuable to allow validators with a broken Attestation Service setup to take themselves out of the loop for serving verifications.

### Current Behavior

Exists in smart contracts, e.g, `removeAttestationSigner`, but not in ContractKit wrappers or CLI.

### Implementation 
- Add wrapper method(s) for `removeAttestationSigner` and `getAttestationSigner`
- Add celocli command `account:deauthorize`. The `run` function for this command should first call `getAttestationSigner` and check that the result matches the account provided to the command. This check should will prevent the call to `removeAttestationSigner` from failing with a confusing error. (Note, this is based on what I'm noticing has been done on other commands so take it with a grain of salt)

**Comment by alecps** [comment] 2022-05-04 10:02
Extension of this work https://github.com/celo-org/celo-monorepo/pull/2230

**Comment by alecps** [comment] 2022-05-04 10:03
Duplicate of https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9535 (now closed)

**Comment by alecps** [comment] 2022-05-04 15:31
Noting that there will likely be complications running the monorepo dev setup on @noisypigeon's M1 laptop. We're budgeting extra time to account for blockers

**Closed as completed** 2022-06-03 20:27 UTC
Labels: good first issue
