### ISSUE TITLE
Devs SNBAT reference deprecated celotool commands

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#311] opened 2019-08-05 19:33 UTC
### Expected Behavior

No `upgrade contracts` command
### Current Behavior

`upgrade contracts` command

**Comment by ashishb** [comment] 2019-08-07 16:25
Duplicate of https://github.com/celo-org/celo-monorepo/issues/262

**Closed as completed by ashishb** 2019-08-07 16:25 UTC
