### ISSUE TITLE
 [Android] App logo is not shown after launching it when app is closed by tapping on device back button. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1276] opened 2019-10-09 12:23 UTC
**App version:** App store v1.4.2, Celo staging v1.4.2, Play store v1.5.0
**Repro on:**  Samsung Galaxy Note9 (8.1.0), Google Pixel 2 XL (9.0)
**Priority:** Low
**Test Account:** 3158095552/[BackupKey](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1. Launch the app. 
2. Make sure user is on ‘Choose Language’ page.
3. Tap device back button to close the app. 
4. Relaunch the app. 
5. Observe 

**Investigation:**
1. Every time the restart App option is shown when the user closing the app by device back button. 
2. Issue does not repro when user relaunched the app after killing it
3. Issue is not reproed if the app is opened after it is backgrounded using the device home button.

**Impact:** Bad user experience
**Current Behavior:** Current Behavior: Celo Logo is not shown and app is not launched after some time it shows the “Restart App” button.
**Expected Behavior:**  Celo logo should shown and Restart App button should instantly 

**Attachment:** [Android_AppLogoIsnotShown.mp4 ](https://drive.google.com/file/d/1R5v-RE2XVmutvL_W-FO6HhKM4g2PnnAu/view?usp=sharing)(Bug Observed at 05 secs)

**Comment by annakaz** [comment] 2019-12-17 23:33
Closing as this is the intended behavior, as the Celo logo page is the loading screen and loading is not required in the behavior described above

**Closed as completed by annakaz** 2019-12-17 23:33 UTC
Labels: bug, quick fix

**Comment by Lss-Ankit** [comment] 2019-12-18 07:22
Okay, thanks @annakaz for the update
