### ISSUE TITLE
User should have access to account key when migrating Valora to a new phone

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#6797] opened 2021-01-28 20:53 UTC
### Expected Behavior

If a user migrates Valora to a different phone, they should still have access to see their account key in the app

### Current Behavior

"account key is stored in the phone’s “secure enclave” for extra security, which is different from where we store all the other app data. apple will make backups off your app data but not data stored in your secure enclave. if a user gets a new phone and restores all their app data from backups, all the valora data will be restored but the account key wont be. this causes an issue because the valora data thinks everything has been restored when it hasnt" - https://celo-org.slack.com/archives/C018VLA3YAK/p1611860474099800

![Screen Shot 2021-01-28 at 11 54 27 AM](https://user-images.githubusercontent.com/15326838/106197666-f8094f80-6180-11eb-9801-b0fee9824782.png)

**Comment by jeanregisser** [comment] 2021-01-29 10:05
Duplicate of https://github.com/celo-org/celo-monorepo/issues/5891

**Closed as completed by jeanregisser** 2021-01-29 10:05 UTC
