### ISSUE TITLE
Users SBAT to see record of requests they made

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#75] opened 2019-07-22 10:12 UTC
### Expected Behavior

After making a payment request, user should be able to see a confirmation of this, and be able to check if their requests have been completed or not.

### Current Behavior

After a request has been made, no confirmation/record of this provided

**Comment by nityas** [comment] 2019-10-02 18:20
dupe of #1170 , closing

**Closed as completed by nityas** 2019-10-02 18:20 UTC
