### ISSUE TITLE
[Android/iOS][Suggestion]'Logout' or 'clear data' option should show in ‘Setting’ page.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1564] opened 2019-11-01 11:32 UTC
App version: Play store build v1.5.1, Test flight build 1.5.1 (14)
Repro on:  Samsung Galaxy Note9 (8.1.0), Google Pixel 2 XL (9.0), iphone 7+ (12.4)
Test Account: 315 954 3987/[BackupKey](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

Repro Steps:  
1) Launch the app. 
2) Tap on the ‘Cog’ icon to open the setting page.
3) The observe logout option is not shown.  

**Suggestion:** Logout or clear data option should show

**Impact:** If the user wants to logout from the app for while due to security reasons log out or clear data option is not shown.

**Comment by annakaz** [comment] 2020-07-14 18:12
Duplicate of https://github.com/celo-org/celo-monorepo/issues/4399

**Closed as completed by annakaz** 2020-07-14 18:12 UTC
