### ISSUE TITLE
Slow navigation between pages | as seen on QR Scan screen

### ISSUE THREAD

**Issue by rohit-dua** [celo-org/celo-monorepo#1131] opened 2019-09-27 17:01 UTC
### Expected Behavior

After the QR scanning is complete in the QR Code Scan Screen, it take a second or two to transition to the next screen. This gives an appearance that QR Scanning is slow but instead the processes after the code scan take most time.

The transition between screens should be faster and/or the user should be shown a loading icon as soon as the data from code is scanned.

**Comment by annakaz** [comment] 2020-07-22 21:15
Closing, duplicate of resolved https://github.com/celo-org/celo-monorepo/issues/898

**Closed as completed by annakaz** 2020-07-22 21:15 UTC
Labels: bug
