### ISSUE TITLE
Add a "Edit Confirmed Numbers" Option to app settings

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4551] opened 2020-07-28 20:43 UTC
### Expected Behavior

add "Edit Confirmed Numbers" in settings above "Reset Account" (will soon be moved to an account page)
This should show a state w/ all mapped phone number(s) and allow revoke on each of them. displaying a success state afterwards

Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=7600%3A66142)
<img width="2385" alt="Screen Shot 2020-08-05 at 5 43 08 PM" src="https://user-images.githubusercontent.com/51388535/89477856-2a427300-d743-11ea-9868-f08dc7ba3ad6.png">

### Current Behavior

No ability to revoke numbers

**Comment by coreycelo** [comment] 2020-08-06 00:35
Added designs

**Comment by coreycelo** [comment] 2020-08-06 01:02
@cmcewen Sounds like there's an open question about whether we can list mappings ad-hoc like this or if a user needs to enter and lookup numbers manually one-by-one.

**Comment by tarikbellamine** [comment] 2020-09-17 22:19
Duplicate of #4637

**Closed as completed by tarikbellamine** 2020-09-17 22:19 UTC
