### ISSUE TITLE
Wallet should use react-native-sms to send SMS invites for both iOS and Android

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#1553] opened 2019-10-31 14:22 UTC
### Expected Behavior

Wallet should use react-native-sms to send SMS invites for both iOS and Android

### Current Behavior

`react-native-sms` was used to implement the SMS invite on iOS.
See https://github.com/celo-org/celo-monorepo/pull/1541
This library can be used for both iOS and Android and we should now use it for Android too to avoid having to maintain 2 different JS implementations.

**Comment by tarikbellamine** [comment] 2020-09-17 20:19
Duplicate of #3693

**Closed as completed by tarikbellamine** 2020-09-17 20:19 UTC
