### ISSUE TITLE
Android: User B does not receive 3 verification codes while User B performing sign up flow using invitation code when User A (indian number) invites User B (indian number) 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3039] opened 2020-03-06 13:18 UTC
**Frequency:** 100%
**iOS App version:** Android Playstore build : 1.6.1 (104794404).
**Repro on Android Device:** Samsung Galaxy S5 (6.0.1), Samsung Galaxy Grand Prime (5.0.1) 
**Testing Account:** 3155641283 /backup Key

**Repro Steps:** 
1) UserA : Launch the app and Login with test account1
2) UserA : Invite User B with SMS using indian phone number 
3) UserB : Receives invitation code in indian phone number and Perform signup flow 
4) UserB : Navigate to ‘Start Verification’ page and Wait for getting verification 
5) UserB : Observe 

**Current Behavior:** User B does not receive 3 verification codes

**Expected Behavior:** User B should be receive 3 verification codes after sending verification code 

**Investigation:** Sometimes UserB gets received only 1 or 2 verification code  

**Attachment1:** [Android_Verification code does not get received.mp4](https://drive.google.com/file/d/1N48dwEKdl9fOcm-sOCeAh7uZMXbKgfu_/view?usp=sharing) (Bug observe at 4:16 min)

**Comment by tarikbellamine** [comment] 2020-09-16 18:43
I believe this has been addressed by the recent verification work.

**Comment by Lss-Ankit** [comment] 2020-10-10 09:14
Hi @tarikbellamine  I have verified issue once but getting verification error while verifying Indian phone number. hence for now i am reopening this ticket. 
Note: I don't have enough money hence not able to check with second time.

**Comment by nityas** [comment] 2020-11-25 15:33
Hi Ankit-- does this still reproduce? downgrading to P2 for now as well

**Comment by Lss-Ankit** [comment] 2020-11-27 13:23
Hi @nityas  I have verified using Android internal build v1.6.0(1004294325)  and Test Flight build v1.6.0(36) & observed that user B able to get 3 verification codes using Indian phone number 
**Devices:** Samsung Galaxy A5(7.0)

**Comment by gnardini** [comment] 2020-11-27 15:47
Closing since it looks fixed and we don't have invitation codes anymore

**Closed as completed by gnardini** 2020-11-27 15:47 UTC
Labels: bug
