### ISSUE TITLE
Remove ODIS timestamp check 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7781] opened 2021-04-28 03:07 UTC
Currently, ODIS requests include a timestamp provided by the client that must be < 5 min old for ODIS to process the request. This is to prevent against replay attacks (see document here https://docs.google.com/document/d/1dvY5pht9MygAsvEIpCEFPq7Bzz9HK-Jh5xB1qWx2UkY/edit). 

Problem: This means that if a client's clock is out of sync they cannot use ODIS. We've received complaints from users about this, so we should move to a different approach

New Solution: We will store all requests in the signer DB. If the signer has already seen a request, we won't deduct from the user's quota. This will allow us to remove timestamps from ODIS requests. 

This will require updating both the signer and combiner. No changes to Valora are needed

**Comment by codyborn** [comment] 2021-04-28 22:58
@tarikbellamine mentioned this is caused by a bug in Valora and will be fixed going fwd. Lowering priority.

**Closed as completed** 2021-04-29 17:57 UTC
