### ISSUE TITLE
celocli fails: missing trie node

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#4099] opened 2020-06-15 11:09 UTC
### Expected Behavior

`celocli validator:signed-blocks` command should work.

### Current Behavior

```
[martinvol@Martins-MBP:~]$ celocli config:get
nodeUrl: https://rc1-forno.celo-testnet.org
[martinvol@Martins-MBP:~]$ celocli validator:signed-blocks --signer 0x83472bf4c9e9b8b2c62693f81d1e8e336b29ef0c

Error: Returned error: missing trie node 2f0319e2afb2fd0755283b4275a300542e4462d33eb8c3e608bbbf7126825f3c (path )
    at Object.ErrorResponse (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at decoratedCallback (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/utils/rpc-caller.js:128:13)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.16.3/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
```

**Comment by eelanagaraj** [comment] 2021-02-19 15:06
couldn't reproduce with CLI `v1.1.0`, closing

**Closed as completed by eelanagaraj** 2021-02-19 15:06 UTC
Labels: bug
