### ISSUE TITLE
Create script to identify addresses that should be rewarded for inviting others

### ISSUE THREAD

**Issue by jbsibille** [celo-org/celo-monorepo#7034] opened 2021-02-10 17:42 UTC
In reality that will be part of the reward service to track escrow events.

**Comment by gnardini** [comment] 2021-03-01 20:00
Closing, this is sort of a duplicate of https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/7276 and the work will be done there.

**Closed as completed by gnardini** 2021-03-01 20:00 UTC
