### ISSUE TITLE
Users SBAT to "send" by pressing "send"

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#956] opened 2019-09-13 05:23 UTC
### Expected Behavior

"Send" button should be re-labeled to "Continue" or "Confirm" button

### Current Behavior

"send" button acts like continue where the actual money transfer happens on the second screen.

![tmp1](https://user-images.githubusercontent.com/389236/64839307-e46d4100-d5ab-11e9-84e2-716b94c5bdcc.png)

**Comment by jmrossy** [comment] 2019-09-17 16:36
@ashishb this is intentional. We want a confirmation screen to allow users to edit and also for us to calculate exact fees. Is there an alternative you'd suggest that still allows for that chance to review?

**Comment by ashishb** [comment] 2019-09-17 16:58
The first screen should say "continue..." In that case.

**Comment by jmrossy** [comment] 2019-09-18 09:05
> The first screen should say "continue..." In that case.

Then how do we clearly differentiate it from Request?

**Comment by jmrossy** [comment] 2019-09-24 15:06
Closing as by design. We can reopen if more discussion is needed.

**Closed as completed by jmrossy** 2019-09-24 15:06 UTC
