### ISSUE TITLE
Users SNBAT escrowed payments that have been claimed

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#983] opened 2019-09-13 19:57 UTC
### Expected Behavior

Users do not see escrowed payments that have been claimed

### Current Behavior

Volpe and I have a ton of escrow notifications from all the invites, even though they have been claimed

**Comment by jmrossy** [comment] 2019-09-24 15:05
This is probably due to the escrow payment fetch caching. If so, this is the 2nd problem that the caching has introduced. Maybe we should remove it.

**Comment by annakaz** [comment] 2019-09-25 15:54
Is this a duplicate of https://github.com/celo-org/celo-monorepo/issues/953?

**Comment by jmrossy** [comment] 2019-09-25 16:28
It is indeed, I'll take that off your hands.

**Closed as completed by jmrossy** 2019-09-25 16:28 UTC
Labels: bug
