### ISSUE TITLE
Users SBAT see faster, always working invite code redemption

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#1689] opened 2019-11-13 18:15 UTC
### Expected Behavior

Invite code always works

### Current Behavior

Invite code can hang or just fail to complete on certain phones

**Comment by cmcewen** [comment] 2019-11-13 18:16
[celo_logs (14).txt](https://github.com/celo-org/celo-monorepo/files/3842760/celo_logs.14.txt)

**Comment by tarikbellamine** [comment] 2020-09-23 20:57
I believe this is a duplicate of #4655 and has been addressed by #4780 as part of the 1.1 release

**Closed as completed by tarikbellamine** 2020-09-23 20:57 UTC
