### ISSUE TITLE
Reports of users unable to exchange CELO

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5273] opened 2020-10-06 16:44 UTC
### Expected Behavior

* CELO should be exchangeable
* 'MAX' function in exchanging CELO should exchange the total CELO balance minus the estimated fee 

### Current Behavior

* Reports in 1.1 about inability to sell CELO for cUSD in app (see logs from tim sent on 10/5)
* 'MAX' function in exchanging CELO does not account for tx fees

**Comment by nityas** [comment] 2020-10-06 16:45
cc @tarikbellamine once we have investigated, the first point listed here might be a blocker for 1.2

**Comment by tarikbellamine** [comment] 2020-10-06 16:59
duplicate of #5258. i also have not seen evidence that this is happening consistently. i've tested it myself and did not encounter the issue but feel like we could be smarter about how we do this regardless

**Closed as completed by tarikbellamine** 2020-10-06 16:59 UTC
Labels: bug
