### ISSUE TITLE
Android] "Failure redeeming code" error is shown when the user tap on "Paste invite code!" from the "Enter Invite Code" screen when invited users install the app from received invite code.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1283] opened 2019-10-10 09:47 UTC
**App version:** Play store build v1.5.0
**Does not repro:** v1.4.2
**Repro on:**  Samsung Galaxy S4 (5.0.1), Samsung j7 prime (6.0.1), Samsung Galaxy A8+ (8.0.0) 
**Priority:** Medium
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** User must have invitation code which is sent by other celo user. 
 
**Repro Steps:** 
1) Launch the app.
2) Install the  by tapping on received invitation code. 
3) Enter the Full name, Select country and enter phone number. 
4) Tap on Continue button. 
5) Set the PIN. 
6) Make sure is on “Enter Invite code” and “Paste invite code!” button is shown. 
7) Tap on  “Paste invite code!” button. 
8) Observe 

**Current Behavior:**  "Failure redeeming code" error is shown 
**Expected Behavior:** Users should be able to paste the invitation code. 
**Attachment:** [Android_PastInviteCodeButtonIssue.MOV](https://drive.google.com/file/d/1uumBGJD8RXJS0a5o7ZGwVX1XrfxF6FDb/view?usp=sharing) (Bug observe after 3:05 sec)

**Comment by Lss-Ankit** [comment] 2019-11-04 08:34
@jmrossy and @cmcewen Verified with Android build v1.5.1 (104694405) (Internal Early Access) and observe that issue is still reproduced
**Issue:** "Failure redeeming code" error is shown when the user tap on "Paste invite code!" from the "Enter Invite Code" screen when invited users install the app from received invite code.

Attachment: [Android_FailureRedeemCode_InviteUser.mp4](https://drive.google.com/file/d/1vMnaaNbI-E1QgZQ-p1gdBO3t86Ke20Wd/view?usp=sharing)

**Comment by jmrossy** [comment] 2019-11-05 09:38
@Lss-Ankit Thanks for confirming.

**Comment by Lss-Ankit** [comment] 2020-01-23 13:47
@jmrossy Verified with Android v1.5.2 (101548777) integration build and observed that issue is still reproduced. 

- "Failure redeeming code" error is shown when the user taps the Continue button from Invite code screen. 

Attachment: [Android_FailureRedeemCode.mp4](https://drive.google.com/file/d/1OES7kKd-DN3-gYlXj0IGx3UosCw5nH9l/view?usp=sharing)

**Comment by annakaz** [comment] 2020-01-23 16:56
This is caused by this celo-blockchain issue: https://github.com/celo-org/celo-blockchain/issues/810

**Comment by annakaz** [comment] 2020-01-28 17:43
Invites fixed on integration / newly deployed `alfajoresstaging` by https://github.com/celo-org/celo-blockchain/pull/825

**Closed as completed by annakaz** 2020-01-28 17:43 UTC
Labels: bug

**Comment by Lss-Ankit** [comment] 2020-01-29 05:42
@annakaz @jmrossy Verified with Android v1.5.2 (101548777) integration build and observed that issue is fixed now. 

Verified on Devices : Samsung Galaxy S5 (6.0.1), Redmi Note 7 Pro (9.0)

'Failure redeeming code' error is not shown after pasting invite code from Enter Invite Code screen.
