### ISSUE TITLE
Validator shown as offline in https://baklava-celostats.celo-testnet.org/

### ISSUE THREAD

**Issue by jboschj** [celo-org/celo-monorepo#2549] opened 2020-01-27 18:25 UTC
### Expected Behavior

My second validator (StakesStone2) should be shown as online in https://baklava-celostats.celo-testnet.org/ because when I check the docker logs it is showing synced.

### Current Behavior

Validator (StakesStone2) is showing as offline in https://baklava-celostats.celo-testnet.org/.

**Comment by hqueue** [comment] 2020-01-27 18:54
@jboschj and i collaborated to run a validator (StakesStone2) and there is one more weird behavior in the stat for `StakesStone2-proxy`.

## Expected Behavior
Stat shows `CELO_VALIDATOR_ADDRESS` as a node address.

## Current Behavior
![image](https://user-images.githubusercontent.com/9247907/73203233-01339b00-4180-11ea-8587-6cdaccf4dc23.png)


Node address of `StakesStone2-proxy` shown in stat is [cda4c3c62b..](https://baklava-blockscout.celo-testnet.org/address/0xcda4c3c62b9592c59c5c867563e02467620b81e2/celo) which is `CELO_VALIDATOR_SIGNER_ADDRESS` for `StakesStone2` .

Node address of `StakesStone-proxy` is correctly [b7b3c854b0..](https://baklava-blockscout.celo-testnet.org/address/0xb7b3c854b00d65208e410a5d16eb54f58dbebbc7/celo) which is `CELO_VALIDATOR_ADDRESS` of `StakesStone`.

We also checked options of proxy node and found that `CELO_VALIDATOR_SIGNER_ADDRESS` is used for `--proxy.proxiedvalidatoraddress` and `--etherbase` as documented in the guide.

## Additional information
`StakesStone2` has changed affiliation about 3 days ago to start collaboration.
And stat says `last block time` is `3 days ago` as below.
![image](https://user-images.githubusercontent.com/9247907/73204341-23c6b380-4182-11ea-8cd3-eaf662875978.png)

I'm afraid changing affiliation of a validator could be a root cause of this issue.

**Comment by H34D** [comment] 2020-02-07 08:01
~Potential duplicate of https://github.com/celo-org/celo-monorepo/issues/2605 fixed with: https://github.com/celo-org/celostats-server/pull/11~

no duplicate

**Comment by H34D** [comment] 2020-02-12 12:15
Hi @jboschj @hqueue,

i did some research on your case and was experiencing a similar behaviour you mentioned. During my test period the `StakesStone-proxy` was active almost all the time. The `StakesStone2-proxy` was marked as offline for most of the time. It still was reporting blocks sporadically. Both of the validators suffered from reconnects to celostats `StakesStone2-proxy` more, `StakesStone-proxy` less. Both nodes were falling behind with block sync (even when connected to celostats)


After some time both were active and reporting to celostats.

<img width="999" alt="Screenshot 2020-02-12 at 13 04 00" src="https://user-images.githubusercontent.com/13647606/74333507-5b477980-4d98-11ea-866b-39094449514d.png">

Please keep the following in mind:
- Validators are marked `offline` when they drop connection to celostats or do not have celostats configured. This does not mean your node is offline.
- Proxies will be `shadowing` parts of the stats data from the validator. This is why it is shown with the name "proxy". Celostats cannot connect to your validator directly for security reasons. 
- A stable internet connection is important for the node to show active in celostats because they have to hold the connection
- Both of your validators have been elected in the different epochs and therefore are setup properly.

**Closed as completed by H34D** 2020-02-12 12:15 UTC
